# Generated by Django 6.0.3 on 2026-05-08 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_categoria_options_alter_despesa_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compartilhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to=settings.AUTH_USER_MODEL)),
                ('shared_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='can_view_from', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'shared_user')},
            },
        ),
    ]
