# Generated by Django 6.0.3 on 2026-05-08 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_compartilhamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='compartilhamento',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compartilhamento',
            name='shared_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebe_acesso', to=settings.AUTH_USER_MODEL),
        ),
    ]
