# Generated by Django 6.0.3 on 2026-05-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_despesa_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='shared_with',
        ),
    ]
