# Generated by Django 6.0.3 on 2026-05-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_remove_despesa_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='tipo',
            field=models.CharField(choices=[('saida', 'Saída'), ('entrada', 'Entrada')], default='saida', max_length=10, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
