# Generated by Django 6.0.3 on 2026-06-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_despesa_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'ordering': ['-data'], 'verbose_name': 'Movimento', 'verbose_name_plural': 'Movimentos'},
        ),
    ]
