# Generated by Django 6.0.3 on 2026-07-06 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_passwordresettoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='despesa',
            index=models.Index(fields=['user'], name='expenses_de_user_id_60f9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='despesa',
            index=models.Index(fields=['data'], name='expenses_de_data_d74a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='despesa',
            index=models.Index(fields=['tipo'], name='expenses_de_tipo_4f9d44_idx'),
        ),
        migrations.AddIndex(
            model_name='despesa',
            index=models.Index(fields=['categoria'], name='expenses_de_categor_7110b0_idx'),
        ),
        migrations.AddIndex(
            model_name='despesa',
            index=models.Index(fields=['user', 'data'], name='expenses_de_user_id_e63363_idx'),
        ),
    ]
