# Generated by Django 6.0.3 on 2026-07-07 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_despesa_expenses_de_user_id_60f9d2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='expenses.categoria', verbose_name='Categoria'),
        ),
    ]
